name: droid_purifier
description: Offline-first Android De-Google and debloat assistant with dynamic safety analysis and rollback.
publish_to: 'none'
version: 1.3.0+5

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
